import image from "./image/productImage.png";
// import productImage02 from "./images/productImage.png";

const Products = [
    {
        id: 1,
        productName: "Fancy Product",
        productRating: 0,
        productPrice02: "$40.00 - $80.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: false,
    },
    {
        id: 2,
        productName: "Special Item",
        productRating: 3,
        productPrice01: "$20.00",
        productPrice02: " $18.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: true,
    },
    {
        id: 3,
        productName: "Sale Item",
        productRating: 0,
        productPrice01: "$50.00",
        productPrice02: " $25.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: true,
    },
    {
        id: 4,
        productName: "Popular Item",
        productRating: 5,
        productPrice02: "$40.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: false,
    },
    {
        id: 5,
        productName: "Sale Item",
        productRating: 0,
        productPrice01: "$50.00",
        productPrice02: " $25.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: true,
    },
    {
        id: 6,
        productName: "Fancy Product",
        productRating: 4,
        productPrice02: "$120.00 - $280.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: false,
    },
    {
        id: 7,
        productName: "Special Item",
        productRating: 5,
        productPrice01: "$20.00",
        productPrice02: " $18.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: true,
    },
    {
        id: 8,
        productName: "Popular Item",
        productRating: 0,
        productPrice02: "$40.00",
        productImage: image,
        disabled: false,
        hidden: true,
        sale: false,
    },
];

export default Products;